baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'eirn'
theme = ["paperesque","hugo-shortcode-gallery"]

## Top level menu



[[params.topmenu]]
  name = "cv"
  url = "cv/"

[[params.topmenu]]
  name = "photography"
  url = "photography/"

[[params.topmenu]]
  name = "recent posts"
  url = "posts/"


