baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'esteban'
theme = ["paperesque","hugo-shortcode-gallery"]

## Top level menu



[[params.topmenu]]
  name = "resume"
  url = "resume/"

[[params.topmenu]]
  name = "photography"
  url = "photography/"

[[params.topmenu]]
  name = "recent posts"
  url = "posts/"


