baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'esteban'
theme = ["paperesque"]

## Top level menu

[[module.imports]]
path = "github.com/mfg92/hugo-shortcode-gallery"

[[params.topmenu]]
  name = "resume"
  url = "resume/"

[[params.topmenu]]
  name = "photography"
  url = "photography/"

[[params.topmenu]]
  name = "recent posts"
  url = "posts/"


