baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'eirn'
theme = ["paperesque","hugo-universal-theme"]


## Top level menu

[[params.topmenu]]
  name = "about"
  url = "about/"

[[params.topmenu]]
  name = "cv"
  url = "cv/"

[[params.topmenu]]
  name = "photography"
  url = "photography/"

[[params.topmenu]]
  name = "recent posts"
  url = "posts/"


